@extends('layouts.app')

@section('page_title', 'Multi-Factor Authentication (2FA)')

@section('content')
<div class="max-w-3xl mx-auto">
    <div class="mb-6 flex items-center justify-between">
        <div>
            <h2 class="text-xl font-bold text-white font-outfit">2FA Security Settings</h2>
            <p class="text-sm text-slate-400 mt-0.5">Secure your super admin account using a Time-based One-Time Password (TOTP).</p>
        </div>
        <a href="{{ route('admin.profile.edit') }}" class="text-sm text-indigo-400 hover:text-indigo-300 font-medium flex items-center gap-1">
            &larr; Back to Profile
        </a>
    </div>

    @if ($errors->any())
        <div class="mb-6 p-4 rounded-xl bg-rose-950/40 border border-rose-800/40 text-rose-200 text-xs font-medium">
            <ul class="list-disc list-inside space-y-1">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="space-y-6">
        @if(!$user->two_factor_enabled)
            <!-- MFA Setup Panel -->
            <div class="bg-slate-900/60 border border-slate-800/60 rounded-2xl p-8 space-y-6">
                <h3 class="text-lg font-semibold text-white border-b border-slate-800/60 pb-3 flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-indigo-400">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    Step 1: Scan the QR Code
                </h3>
                <p class="text-sm text-slate-300">
                    Scan the QR code below using your authenticator app (such as Google Authenticator, Microsoft Authenticator, Authy, or 1Password) on your mobile device.
                </p>

                <div class="flex flex-col md:flex-row items-center gap-8 justify-center bg-slate-950/40 p-6 rounded-xl border border-slate-800/40">
                    <div class="bg-white p-3 rounded-xl shrink-0 shadow-lg">
                        {!! SimpleSoftwareIO\QrCode\Facades\QrCode::size(180)->margin(0)->generate($qrCodeUrl) !!}
                    </div>
                    <div class="space-y-3 max-w-sm">
                        <p class="text-xs text-slate-400 font-medium uppercase tracking-wider">Manual Account Key</p>
                        <div class="bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-3 font-mono text-sm text-indigo-400 tracking-wider break-all flex items-center justify-between">
                            <span>{{ $user->two_factor_secret }}</span>
                        </div>
                        <p class="text-xs text-slate-500">
                            If you cannot scan the QR code, manually add a new account in your app with the key above.
                        </p>
                    </div>
                </div>

                <form method="POST" action="{{ route('admin.mfa.enable') }}" class="border-t border-slate-800/60 pt-6 space-y-6">
                    @csrf
                    <h3 class="text-lg font-semibold text-white flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-indigo-400">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Step 2: Enter Verification Code
                    </h3>
                    <p class="text-sm text-slate-300">
                        Enter the 6-digit verification code generated by your authenticator app to verify that setup was successful and enable Multi-Factor Authentication.
                    </p>

                    <div class="max-w-xs">
                        <label for="code" class="block text-sm font-medium text-slate-300 mb-2">Authenticator Verification Code</label>
                        <input type="text" id="code" name="code" required placeholder="000000" maxlength="6"
                               class="w-full bg-slate-800/50 border border-slate-700/60 rounded-xl px-4 py-3 text-slate-100 text-sm font-mono tracking-widest text-center focus:outline-none focus:border-indigo-500">
                    </div>

                    <button type="submit" class="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-6 py-3 rounded-xl transition-all text-sm cursor-pointer shadow-md shadow-indigo-600/10">
                        Verify & Enable 2FA
                    </button>
                </form>
            </div>
        @else
            <!-- MFA Active Panel -->
            <div class="bg-slate-900/60 border border-slate-800/60 rounded-2xl p-8 space-y-6">
                <div class="flex items-start gap-4">
                    <div class="w-12 h-12 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center shrink-0">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                    <div>
                        <h3 class="text-lg font-semibold text-white">Multi-Factor Authentication (2FA) is Active</h3>
                        <p class="text-sm text-slate-400 mt-1">Your account is secured with 2FA. Every time you log in, you will be prompted for an authenticator verification code.</p>
                    </div>
                </div>

                <form method="POST" action="{{ route('admin.mfa.disable') }}" class="border-t border-slate-800/60 pt-6 space-y-6">
                    @csrf
                    <h4 class="text-base font-semibold text-rose-400 flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                        </svg>
                        Disable Multi-Factor Authentication
                    </h4>
                    <p class="text-sm text-slate-300">
                        If you need to disable 2FA, confirm your current password below to turn it off. Disabling 2FA reduces your account security.
                    </p>

                    <div class="max-w-sm">
                        <label for="password" class="block text-sm font-medium text-slate-300 mb-2">Confirm Your Password</label>
                        <input type="password" id="password" name="password" required placeholder="Enter current password"
                               class="w-full bg-slate-800/50 border border-slate-700/60 rounded-xl px-4 py-3 text-slate-100 text-sm focus:outline-none focus:border-rose-500">
                    </div>

                    <button type="submit" class="bg-rose-600 hover:bg-rose-500 text-white font-semibold px-6 py-3 rounded-xl transition-all text-sm cursor-pointer shadow-md shadow-rose-600/10">
                        Disable 2FA Security
                    </button>
                </form>
            </div>
        @endif
    </div>
</div>
@endsection
